version: '3'

services:
 minio1:
  image: minio/minio
  volumes:
   - bluxomous-minio1:/export
  expose:
    - 9000
  env_file: .env
  command: server /export
 # minio2:
 #  image: minio/minio
 #  volumes:
 #   - bluxomous-minio2:/export
 #  expose:
 #   - 9000 
 #  env_file: .env
 #  command: server /export
 # minio3:
 #  image: minio/minio
 #  volumes:
 #   - bluxomous-minio3:/export
 #  expose:
 #    - 9000
 #  env_file: .env
 #  command: server /export
 # minio4:
 #  image: minio/minio
 #  volumes:
 #   - bluxomous-minio4:/export
 # expose:
 #  - 9000
 #  env_file: .env
 #  command: server /export
networks:
  default:
    external:
      name: nginx-proxy

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  bluxomous-minio1:
  # bluxomous-minio2:
  # bluxomous-minio3:
  # bluxomous-minio4: