version: '3'

services:
 minio1:
  image: pixelchrome/minio-arm
  volumes:
   - vol-minio1:/export
   - /mnt/minio/prod,dst=/export
  ports:
   - "9001:9000"
  expose:
   - 9000
  networks:
   - minio_distributed
   - ntw_minio
  env_file: .env
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
  deploy:
    placement:
      constraints:
       - node.hostname == node1
 minio2:
  image: pixelchrome/minio-arm
  volumes:
   - vol-minio2:/export
   - /mnt/minio/prod,dst=/export
  ports:
   - "9002:9000"
  expose:
   - 9000
  networks:
   - minio_distributed
   - ntw_minio
  env_file: .env
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
  deploy:
    placement:
      constraints:
       - node.hostname == node2
 minio3:
  image: pixelchrome/minio-arm
  volumes:
   - vol-minio3:/export
   - /mnt/minio/prod,dst=/export
  ports:
   - "9003:9000"
  expose:
   - 9000
  networks:
   - minio_distributed
   - ntw_minio
  env_file: .env
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
  deploy:
    placement:
      constraints:
       - node.hostname == node3
 minio4:
  image: pixelchrome/minio-arm
  volumes:
   - vol-minio4:/export
   - /mnt/minio/prod,dst=/export
  ports:
   - "9004:9000"
  expose:
   - 9000
  networks:
   - minio_distributed
   - ntw_minio
  env_file: .env
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
  deploy:
    placement:
      constraints:
       - node.hostname == node3
volumes:
  vol-minio1:
  vol-minio2:
  vol-minio3:
  vol-minio4:

networks:
  minio_distributed:
    driver: overlay
  # default:
  #   external:
  #     name: nginx-proxy