version: '3'

services:
 minio1:
  image: minio/minio
  volumes:
   - minio1-data:/export
   # - /mnt/minio/prod:/export
  ports:
   - "9001:9000"
  expose:
   - 9000
  networks:
   - minio_distributed
  env_file: .env
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
  deploy:
    placement:
      constraints:
       - node.labels.arch == x86
 minio2:
  image: minio/minio
  volumes:
   - minio2-data:/export
   # - /mnt/minio/prod:/export
  ports:
   - "9002:9000"
  expose:
   - 9000
  networks:
   - minio_distributed
  env_file: .env
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
  deploy:
    placement:
      constraints:
       - node.labels.arch == x86
 minio3:
  image: minio/minio
  volumes:
   - minio3-data:/export
   # - /mnt/minio/prod:/export
  ports:
   - "9003:9000"
  expose:
   - 9000
  networks:
   - minio_distributed
  env_file: .env
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
  deploy:
    placement:
      constraints:
       - node.labels.arch == x86
 minio4:
  image: minio/minio
  volumes:
   - minio4-data:/export
   # - /mnt/minio/prod:/export
  ports:
   - "9004:9000"
  expose:
   - 9000
  networks:
   - minio_distributed
  env_file: .env
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
  deploy:
    placement:
      constraints:
       - node.labels.arch == x86
volumes:
  minio1-data:
  minio2-data:
  minio3-data:
  minio4-data:

networks:
  minio_distributed:
    driver: overlay
  # default:
  #   external:
  #     name: nginx-proxy