version: '3'

services:
 minio1:
  image: pixelchrome/minio-arm
  volumes:
   - vol-minio1:/export
  expose:
   - 9000
  networks:
   - minio_distributed
  env_file: .env
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export
  deploy:
    placement:
      constraints:
       - node.hostname == node1
volumes:
  vol-minio1:

networks:
 minio_distributed:
  driver: overlay
  default:
    external:
      name: nginx-proxy