version: '3'

services:
 minio1:
  image: pixelchrome/minio-arm
  volumes:
   - minio1-data:/export
   # - /mnt/minio/prod:/export
  # networks:
  #  - minio_distributed
  env_file: .env
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
  deploy:
    placement:
      constraints:
       - node.hostname == node1
 minio2:
  image: pixelchrome/minio-arm
  volumes:
   - minio2-data:/export
   # - /mnt/minio/prod:/export
  # networks:
  #  - minio_distributed
  env_file: .env
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
  deploy:
    placement:
      constraints:
       - node.hostname == node2
 minio3:
  image: pixelchrome/minio-arm
  volumes:
   - minio3-data:/export
   # - /mnt/minio/prod:/export
  # networks:
  #  - minio_distributed
  env_file: .env
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
  deploy:
    placement:
      constraints:
       - node.hostname == node3
 minio4:
  image: pixelchrome/minio-arm
  volumes:
   - minio4-data:/export
   # - /mnt/minio/prod:/export
  # networks:
  #  - minio_distributed
  env_file: .env
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
  deploy:
    placement:
      constraints:
       - node.hostname == node3
# volumes:
  # minio1-data:
#   minio2-data:
#   minio3-data:
#   minio4-data:

networks:
  minio_distributed:
    driver: overlay
  # default:
  #   external:
  #     name: nginx-proxy
