version: '3'

services:
 minio1:
  image: minio/minio
  volumes:
   - vol-minio1:/export
  ports:
   - "9001:9000"
  env_file: .env
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
 minio2:
  image: minio/minio
  volumes:
   - vol-minio2:/export
  ports:
   - "9002:9000"
  env_file: .env
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
 minio3:
  image: minio/minio
  volumes:
   - vol-minio3:/export
  ports:
   - "9003:9000"
  env_file: .env
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
 minio4:
  image: minio/minio
  volumes:
   - vol-minio4:/export
  ports:
   - "9004:9000"
  env_file: .env
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 


## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  vol-minio1:
  vol-minio2:
  vol-minio3:
  vol-minio4:
